version: '3.4'

services:
  gateway.webapi:
    image: ${DOCKER_REGISTRY-}gatewaywebapi
    build:
      context: .
      dockerfile: Gateway.WebApi\Dockerfile

  product.webapi:
    image: ${DOCKER_REGISTRY-}productwebapi
    build:
      context: .
      dockerfile: Product.WebApi\Dockerfile

  customer.webapi:
    image: ${DOCKER_REGISTRY-}customerwebapi
    build:
      context: .
      dockerfile: Customer.WebApi\Dockerfile